### ISSUE TITLE
move Nova{Compute,Evacuate} to openstack-resource-agents?

### ISSUE THREAD

**Issue by aspiers** [beekhof/osp-ha-deploy#18]
Hi all,

As you will have seen today, I've finally started on revitalizing https://github.com/madkiss/openstack-resource-agents by [madkiss/openstack-resource-agents#22: moving it to stackforge](https://github.com/madkiss/openstack-resource-agents/issues/22).  Would you be open to the idea of moving the `NovaCompute` and `NovaEvacuate` resource agents to the new repository when it's ready?  I have a bunch of patches I would like to contribute to these RAs but I guess it doesn't make much sense for me to contribute them to an OSP-centric repo since I have no clue about OSP and might end up breaking something or messing with your release cycle ;-)  And I guess the same might apply for Ubuntu-oriented OpenStack developers who might want to use them in the future.

Cheers,
Adam

**Comment by aspiers** [comment]
Another consideration is that these two RAs are very much co-dependent with [`fence_compute.py`](https://github.com/ClusterLabs/fence-agents/blob/master/fence/agents/compute/fence_compute.py), so I wonder if it might make sense to move them all to the same repo?  I would imagine that since this is a fairly new area of development, things could change quite a bit of the next 6-12 months (at least, probably more often than the [`fencing.py`](https://github.com/ClusterLabs/fence-agents/blob/master/fence/agents/lib/fencing.py.py) API changes). Alternately we could introduce some kind of versioning of the interface between them, to ensure compatibility.

**Comment by fabbione** [comment]
On 10/17/2015 7:57 PM, Adam Spiers wrote:

> Another consideration is that these two RAs are very much co-dependent
> with |fence_compute.py|
> https://github.com/ClusterLabs/fence-agents/blob/master/fence/agents/compute/fence_compute.py,
> so I wonder if it might make sense to move them all to the same repo? I
> would imagine that since this is a fairly new area of development,
> things could change quite a bit of the next 6-12 months (at least,
> probably more often than the |fencing.py|
> https://github.com/ClusterLabs/fence-agents/blob/master/fence/agents/lib/fencing.py.py
> API changes). Alternately we could introduce some kind of versioning of
> the interface between them, to ensure compatibility.

fence_compute is already upstream in fence-agents and it´s hard to split
it out due to the build system for fence-agents itself.

I don´t see a problem to just keep fence-compute where it is, since we
are all part of that upstream and yes I agree we should move NovaCompute
and NovaEvacuate in the new repo.

Let me check Monday if by any chance there are patches not pushed to
this git repo and we can copy them over.

Fabio

**Comment by aspiers** [comment]
> fence_compute is already upstream in fence-agents and it´s hard to split
> it out due to the build system for fence-agents itself.

At the moment the build system doesn't seem to do much with it except substitute `@FENCEAGENTSLIBDIR@` for some path.  However I could be missing other details, e.g. there seems to be a test framework in that repo which I guess could potentially be harnessed in the future to test it.

> I don´t see a problem to just keep fence-compute where it is, since we
> are all part of that upstream

I agree, I have absolutely no problem with keeping it where it is.  It was just a random idea to move it but there are pros and cons either way, so that's totally fine to leave it there.

> and yes I agree we should move NovaCompute and NovaEvacuate in the new repo.
> 
> Let me check Monday if by any chance there are patches not pushed to
> this git repo and we can copy them over.

OK great, thanks a lot!  I've never submitted a request for a new OpenStack project before, so I don't know how long we're likely to have to wait for the repo to be set up.

**Comment by fabbione** [comment]
On 10/18/2015 3:13 AM, Adam Spiers wrote:

> ```
> fence_compute is already upstream in fence-agents and it´s hard to split
> it out due to the build system for fence-agents itself.
> ```
> 
> At the moment the build system doesn't seem to do much with it except
> substitute |@FENCEAGENTSLIBDIR@| for some path. However I could be
> missing other details, e.g. there seems to be a test framework in that
> repo which I guess could potentially be harnessed in the future to test it.

Right, it does a bit more than that, like generating man pages, wiki
pages, metadata for puppet and the test framework that´s in the work.
Moving it outside, might means duplicating a lot of that bits, or
potentially changing fence-agents package to ship a -devel subpackage
just for one agent.
Considering that we drive also fence-agents via ClusterLabs/ github and
we can merge as fast as necessary, it´s more troubles to move than to
keep it where it is :)

> ```
> I don´t see a problem to just keep fence-compute where it is, since we
> are all part of that upstream
> ```
> 
> I agree, I have absolutely no problem with keeping it where it is. It
> was just a random idea to move it but there are pros and cons either
> way, so that's totally fine to leave it there.
> 
> ```
> and yes I agree we should move NovaCompute and NovaEvacuate in the
> new repo.
> 
> Let me check Monday if by any chance there are patches not pushed to
> this git repo and we can copy them over.
> ```
> 
> OK great, thanks a lot! I've never submitted a request for a new
> OpenStack project before, so I don't know how long we're likely to have
> to wait for the repo to be set up.

No worries at all, we are not in a rush anyway.

Fabio

**Comment by aspiers** [comment]
> Right, it does a bit more than that, like generating man pages, wiki
> pages, metadata for puppet and the test framework that´s in the work.
> Moving it outside, might means duplicating a lot of that bits, or
> potentially changing fence-agents package to ship a -devel subpackage
> just for one agent.
> Considering that we drive also fence-agents via ClusterLabs/ github and
> we can merge as fast as necessary, it´s more troubles to move than to
> keep it where it is :)

Ahah OK, thanks for the explanation.  I thought I might be missing something :)

**Comment by aspiers** [comment]
FYI [I have just announced that the new project is ready](https://github.com/madkiss/openstack-resource-agents/issues/22#issuecomment-149853094) so we can start to think about importing these two RAs.  Any preferences on whether we should attempt to preserve the existing git history for them from this repo?  I know the git voodoo for doing this, but maybe you would prefer a direct import of the files?  I don't really mind either way.

BTW which of you guys are coming to Tokyo?

**Comment by aspiers** [comment]
P.S. [new #openstack-ha IRC channel on FreeNode](http://lists.openstack.org/pipermail/openstack-dev/2015-October/077735.html)

**Comment by aspiers** [comment]
This was done ages ago.
